### ISSUE TITLE
[1.10.2] Plugin will not load properly

### ISSUE THREAD

**Issue by runescapejon** [Redrield/chatcoloursplus#3]
Hello i am on 1.10.2 and the plugin load right but it will give an error when i write the command /ccp
here is the log from it's loading point https://pastebin.com/jUNKuyuZ
and here what happen when someone run /ccp command - https://pastebin.com/VUJMfN7u
SpongeForge - 1.10.2-2281-5.2.0-BETA-2472

**Comment by Redrield** [comment]
You're going to have to try running with version 1.2 off the plugin. Versions past that use a new system for data manipulator registration, and it isn't backwards compatible.

**Comment by runescapejon** [comment]
oh alright no a problem thanks tho
